default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gondolas_development


test:
  <<: *default
  database: gondolas_test

production:
  <<: *default
  database: gondolas_production
  username: <%= ENV['GONDOLAS_DATABASE_USER'] %>
  password: <%= ENV['GONDOLAS_DATABASE_PASSWORD'] %>
